Obtener tiempos de lectura de JSON en Python
TT2024-B106/similarity-measures pull request #34
Opened 2024-07-21 23:30 UTC by MarcoOrtegaF

Fixes #29

- Ahora el ECATEPEC.json esta en la carpeta assets

- El notebook de TemposLectura esta actualizado con graficas y el benchmarking en C++

2024-07-29 01:21 UTC, edoomm requested changes
Elimina el GeoJSON de `examples` y poner las funciones de `plot_time_vs_step_size` y demás en `plotfn.py`

2024-08-11 20:11 UTC, edoomm requested changes
Hmmm ya son muchos GeoJSON y no sé si nos sea conveniente tener todo esto aquí en este repositorio, ni los estamos usando y no creo los vayamos a usar todos ¿? No sé que opinen @JavierMung @MarcoOrtegaF yo preferiría que creemos otro repositorio aparte para todos estos assets

2024-08-11 20:19 UTC, MarcoOrtegaF commented
> Hmmm ya son muchos GeoJSON y no sé si nos sea conveniente tener todo esto aquí en este repositorio, ni los estamos usando y no creo los vayamos a usar todos ¿? No sé que opinen @JavierMung @MarcoOrtegaF yo preferiría que creemos otro repositorio aparte para todos estos assets

Pero igual no estorban en este repo ?no?
Siento que si los usamos vamos a tener que andar cambiando entre diferentes repos, pero igual yo diria que le preguntemos al doc Amilcar para que nos diga que fin tienen tantos JSON y despues decidimos que hacemos con ellos, ?que dicen @edoomm  y @JavierMung ?

2024-08-11 20:21 UTC, edoomm commented
va, es que igual pongo peros, porque no sé cuánto pesen ¿? jajaja tenemos límite aquí en el Github, no me gustaría que el repo empiece a chillar porque andamos excediendo el límite de algo que no estamos usando por el momento o que nos puede abarcar mucho espacio en nuestras PCs

2024-08-11 20:31 UTC, MarcoOrtegaF commented
Según yo no son tan grandes, no veo más de 200 trayectorias en el archivo más grande, pero mejor lo revisamos en la reunión de hoy y ya vemos que hacer con esos assets mientras dejamos la pull abierta

2024-08-14 04:07 UTC, edoomm commented on assets/GEOJSON 2/Atizapan.json
este que pedo

2024-08-14 04:08 UTC, edoomm commented on utils/plotfn.py
> +def test():
quita esta funcion

2024-08-20 04:56 UTC, edoomm commented
Acá esta tu pedo
![image](https://github.com/user-attachments/assets/e8f4bd2a-8353-4a5c-98a8-a3a50afbf5fc)

Que es en tu jupyter, andas importando 2 veces `json` por ejemplo en la primera chilladera del ruff
![image](https://github.com/user-attachments/assets/4bce5e0c-2d04-4e5f-a75a-d364707dcb98)
![image](https://github.com/user-attachments/assets/e7966c60-f113-43f4-8ec8-b5aa96d2bb1d)

Chécale bien los errores que te anda arrojando mi todo tibio

2024-08-20 15:28 UTC, MarcoOrtegaF commented
Ya corregi los errores de los Notebooks mi tio @edoomm, en los tuyos tambien habia problemas con las librerias, tambien ya estan corregidos

2024-08-23 00:26 UTC, edoomm approved these changes
Te faltó meter tu función para graficar en `plotfn.py` y te sobra una celda de código en tu notebook, pero ya la apruebo para que no chillen las otras PR

2024-08-23 00:27 UTC, merged