Dtw
TT2024-B106/similarity-measures pull request #5
Opened 2024-03-17 02:43 UTC by JavierMung

Check pls

2024-03-20 23:49 UTC, edoomm commented
Hasta apenas te vengo agarrando el pedo con tu PR y con las implementaciones que te andas aventando.

Esta branch ya nos podría servir más para cuando implementemos la librería de C++, así como estructuraste tu directorio de `PruebasAlgoritmos` es como debería quedar después la librería que hagamos con todos los algoritmos que vayamos a implementar en C++, igual lo del patrón de diseño se incluiría aquí.

¿Te parece, así como dijimos que este repo se quede de prubeas, dejemos esta branch como esquema para la librería en C++ que implementemmos después? Podríamos renombrar esta branch de `dtw` a `cpp-lib-schema` y ya tenerla como guía después.

Ahorita yo pienso nos es mejor tener las implementaciones de los algoritmos así solitos (sin patrón de diseño, los puros archivos `cpp`), para poder andar analizandolos y haciendo distintas pruebas de integración `C++`-`Python`.

¿Cómo ves?
De todas maneras, te hago review, pero igual si estás de acuerdo, cerrariámos esta PR y renombraríamos tu branch.

2024-03-21 00:00 UTC, edoomm requested changes

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/Headers/Algoritmos.h
> +    double distanceAbsolut(double x, double y);
Acá tienes un typo, debería ser: `distanceAbsolute`, `Absolut` es el vodka jajaja

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/Headers/Coordinates.h
Esto igual (para futuras referencias), yo creo que las estructuras y manejo de datos, sería responsabilidad de Python, pero vamos viendo, no estoy igual seguro

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/PruebasAlgoritmos.sln
Esto debería ir a `.gitignore`, creo nomás tú usas VS jaja e igual a como veo, no vamos a ejecutar código en C++, solo compilar y construir librerías dinámicas, que es lo que el `Makefile` ya anda haciendo con el euclideano.

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/PruebasAlgoritmos.vcxproj
`gitignore`

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/PruebasAlgoritmos.vcxproj.filters
`gitignore`

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/PruebasAlgoritmos.vcxproj.user
`gitignore`

2024-03-21 00:00 UTC, edoomm commented on PruebasAlgoritmos/Src/Algorithms/DTW.cpp
> +#include "../../Headers/DTW.h"
(Igual para futuras referencias) Habría que investigar que show con la carpeta `include` que va al mismo nivel de `src`, checa como lo tiene [GEOS](https://github.com/libgeos/geos) en su [algoritmo de Hausdorff](https://github.com/libgeos/geos/blob/main/src/algorithm/distance/DiscreteHausdorffDistance.cpp#L19) solo hacen:

```c++
#include <geos/algorithm/distance/DiscreteHausdorffDistance.h>
```

Nosotros podríamos igual hacer algo tipo:
```c++
#include <algorithms/dtw.h>
```

Solo que la vez que lo intenté hacer así nomás, no funcionaba jajaja, pero siento que se ve mejor así, más práctico. No sé si hay que configurar algo

2024-03-22 17:52 UTC, JavierMung commented on PruebasAlgoritmos/Headers/Algoritmos.h
> +    double distanceAbsolut(double x, double y);
Jajajaja es verdad, hay que renombrarlo jaja

2024-03-22 17:53 UTC, JavierMung commented on PruebasAlgoritmos/PruebasAlgoritmos.sln
Si, ya vi, lo quito y lo agrego al .gitignore

2024-03-22 17:54 UTC, JavierMung commented on PruebasAlgoritmos/PruebasAlgoritmos.vcxproj
✅✅

2024-03-22 17:54 UTC, JavierMung commented on PruebasAlgoritmos/PruebasAlgoritmos.vcxproj.filters
✅✅

2024-03-22 17:54 UTC, JavierMung commented on PruebasAlgoritmos/PruebasAlgoritmos.vcxproj.user
✅✅

2024-03-22 17:57 UTC, JavierMung commented on PruebasAlgoritmos/Src/Algorithms/DTW.cpp
> +#include "../../Headers/DTW.h"
Lo modificamos, a mi tampoco me agrada tener carpetas fuera de, pero era para que viera nivel de carpetas un orden ya que las cabeceras no contienen código solo la declaración de las funciones, pero lo analizamos ✅✅

2024-03-22 18:57 UTC, JavierMung commented on PruebasAlgoritmos/Headers/Coordinates.h
Lo revisamos, igual por el momento se queda

2024-03-22 19:15 UTC, JavierMung commented
Concuerdo en dejar esta rama para los algoritmos, sin embargo, creo que si es necesario que desde un principio se comiencen a implementar las clases de cada algoritmo, por dos razones, en primer lugar hacer doble trabajo al crear el código de un algoritmo en un solo archivo con sus métodos y después refactorizarlo para el patrón de diseño se me haría una perdida de tiempo y en segundo lugar que el heredar de una interface (clase abstracta)  nos va a permitir hacer pruebas mucho más rápido, corregir errores y separar responsabilidades, además que el código queda más limpio y legible. Yo sugeriría si dejar esta rama como pruebas de los algoritmos pero que si se fueran implementando de acuerdo al patrón de diseño.

2024-03-26 22:21 UTC, edoomm commented
No había visto tu último comentario, perdón, de hecho te iba a decir que qué show jajaja

Pero va, mira, si te parece, dejamos esta rama así y en cuanto termine #7, trabajo sobre esta rama y una nueva que cree para el algoritmo de Frechet y voy testeando la integración a Python (como ando haciendo en los [examples](https://github.com/TT2024-B106/similarity-measures/tree/analysis/examples)), CI/CD, pruebas y demás; para ver que nos conviene más, si ya utilizar el patrón de diseño de una o no (igual, no creo nos ahorremos el doble trabajo si lo usamos o no, saldrán cosas que modificar). Solo por fa, te encargo le des push a los cambios (para trabajar sobre la última versión de esta rama) e igual pongas un test, algo tipo `test_dtw.cpp`, algo como se tiene en [`test_euclidean.cpp`](https://github.com/TT2024-B106/similarity-measures/blob/main/tests/test_euclidean.cpp) (que igual tengo que modificar, porque ahi estoy usando librerías dinámicas y aún no sabemos, si sí vayamos a usarlas), igual en #7 pienso de una agregar un workflow para tests, entonces igual nos serviría tener ya algunas pruebas y también sepamos que resultados esperar.

Igual, no se te olvidé darle `Resolve` a los conversaciones que ya hayas hecho cambios o así, deje 2 conversaciones sin resolver que son las de [`Coordinates.h`](https://github.com/TT2024-B106/similarity-measures/pull/5#discussion_r1536058521) (que habrá que revisar) y [`DTW.cpp`](https://github.com/TT2024-B106/similarity-measures/pull/5#discussion_r1533066490) (que tiene que ver con #6).

En resumen:

- [ ] Darle push a los cambios que ya marque como conversaciones resueltas
- [ ] Implementación de test
- [ ] Si puedes, igual aventarte #6 de una, estaría chido tmb

Por fa, ¿no? Para que andemos avanzando a esto(:

2024-06-17 01:28 UTC, closed without merging